

#ifndef _RTPS_SECURITY_COMMON_PARTICIPANTGENERICMESSAGE_H_
#define _RTPS_SECURITY_COMMON_PARTICIPANTGENERICMESSAGE_H_

#include <fastdds/rtps/security/common/ParticipantGenericMessage.h>

#endif // _RTPS_SECURITY_COMMON_PARTICIPANTGENERICMESSAGE_H_
