

#ifndef _FASTRTPS_RTPS_NETWORK_SENDERRESOURCE_H_
#define _FASTRTPS_RTPS_NETWORK_SENDERRESOURCE_H_

#include <fastdds/rtps/transport/SenderResource.h>

#endif /* _FASTRTPS_RTPS_NETWORK_SENDERRESOURCE_H_*/
