

#ifndef _RTPS_SECURITY_EXCEPTIONS_SECURITYEXCEPTION_H_
#define _RTPS_SECURITY_EXCEPTIONS_SECURITYEXCEPTION_H_

#include <fastdds/rtps/security/exceptions/SecurityException.h>

#endif // _RTPS_SECURITY_EXCEPTIONS_SECURITYEXCEPTION_H_
